# Generated by Django 2.1 on 2018-08-09 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('updated',)},
        ),
    ]
