# Generated by Django 2.1 on 2018-08-26 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0003_auto_20180825_2114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Messages',
        ),
    ]
