# Generated by Django 2.0.5 on 2018-08-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180813_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=12),
            preserve_default=False,
        ),
    ]
