# Generated by Django 2.0.5 on 2018-08-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_by',
            field=models.CharField(choices=[('1', 'cash'), ('2', 'bank transfer'), ('3', 'credit card'), ('4', 'paypal')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
