# Generated by Django 2.0.5 on 2018-08-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180819_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pay_by',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=12),
            preserve_default=False,
        ),
    ]
